2024-12-09 11:33:50,139 ERROR: Exception on /rides/request [POST] [in /usr/local/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/utils.py", line 29, in decorated
    return f(*args, **kwargs)
  File "/app/app/routes.py", line 69, in create_ride_request
    current_app.kafka_producer.send(current_app.config['KAFKA_TOPIC'], ride_request)
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 581, in send
    value_bytes = self._serialize(
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/app/app/__init__.py", line 26, in <lambda>
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
2024-12-09 11:37:28,955 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 11:37:52,294 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-09 11:37:52,350 ERROR: Exception on /rides/request [POST] [in /usr/local/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/utils.py", line 29, in decorated
    return f(*args, **kwargs)
  File "/app/app/routes.py", line 69, in create_ride_request
    current_app.kafka_producer.send(current_app.config['KAFKA_TOPIC'], ride_request)
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 581, in send
    value_bytes = self._serialize(
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/app/app/__init__.py", line 26, in <lambda>
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2024-12-09 11:39:00,150 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 11:40:09,593 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-09 11:40:09,670 ERROR: Exception on /rides/request [POST] [in /usr/local/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/utils.py", line 29, in decorated
    return f(*args, **kwargs)
  File "/app/app/routes.py", line 69, in create_ride_request
    current_app.kafka_producer.send(current_app.config['KAFKA_TOPIC'], ride_request)
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 581, in send
    value_bytes = self._serialize(
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/app/app/__init__.py", line 26, in <lambda>
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2024-12-09 11:50:13,788 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 11:50:43,168 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-09 11:50:43,278 ERROR: Exception on /rides/request [POST] [in /usr/local/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/utils.py", line 29, in decorated
    return f(*args, **kwargs)
  File "/app/app/routes.py", line 67, in create_ride_request
    current_app.kafka_producer.send(current_app.config['KAFKA_TOPIC'], ride_request)
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 581, in send
    value_bytes = self._serialize(
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/app/app/__init__.py", line 26, in <lambda>
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
2024-12-09 11:51:22,455 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 11:52:27,178 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-09 11:52:27,402 INFO: Ride request created successfully: a77a4464-ebee-4c2e-a00b-8d62fca41631 [in /app/app/routes.py:72]
2024-12-09 12:27:27,615 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 12:28:42,537 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-09 12:28:42,636 INFO: Ride request created successfully: 805c6f36-7439-47ee-9c71-8502d480c080 [in /app/app/routes.py:72]
2024-12-09 12:34:53,018 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-09 12:34:53,134 INFO: Ride request created successfully: 7679e6b7-4f1a-474f-8c1c-035f1e98cc9a [in /app/app/routes.py:72]
2024-12-15 16:36:50,740 INFO: Application startup [in /app/app/logger.py:19]
2024-12-15 18:56:58,132 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-15 18:56:58,441 INFO: Ride request created successfully: a4a6bbcc-c0e2-4a0f-be86-a7348f4c4ee2 [in /app/app/routes.py:72]
2024-12-15 18:58:34,246 INFO: Fetching ride status by ID: a4a6bbcc-c0e2-4a0f-be86-a7348f4c4ee2 [in /app/app/routes.py:79]
2024-12-15 18:58:34,261 INFO: Ride status: PENDING [in /app/app/routes.py:84]
2024-12-15 18:58:54,797 INFO: Fetching ride status by ID: a4a6bbcc-c0e2-4a0f-be86-a7348f4c4ee2 [in /app/app/routes.py:79]
2024-12-15 18:58:54,802 INFO: Ride status: PENDING [in /app/app/routes.py:84]
2024-12-15 19:06:02,108 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-15 19:06:02,264 INFO: Ride request created successfully: 1bf61cef-1dcc-4248-9de2-ccc557f8393d [in /app/app/routes.py:72]
2024-12-15 20:27:59,764 INFO: Application startup [in /app/app/logger.py:19]
2024-12-15 20:32:45,623 INFO: Application startup [in /app/app/logger.py:19]
2024-12-15 20:34:56,009 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
